#!/bin/bash
set -euo pipefail

ADMIN_ROLE="${DB_USERNAME:-plusdate_admin}"
ADMIN_PASSWORD="${DB_PASSWORD:-plusdate_admin_password}"
READ_ROLE="${DB_READ_USERNAME:-plusdate_app_read}"
READ_PASSWORD="${DB_READ_PASSWORD:-plusdate_read_password}"
WRITE_ROLE="${DB_WRITE_USERNAME:-plusdate_app_write}"
WRITE_PASSWORD="${DB_WRITE_PASSWORD:-plusdate_write_password}"
APP_DB="${POSTGRES_DB:-plusdate}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DB" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${READ_ROLE}') THEN
        CREATE ROLE ${READ_ROLE} LOGIN PASSWORD '${READ_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${WRITE_ROLE}') THEN
        CREATE ROLE ${WRITE_ROLE} LOGIN PASSWORD '${WRITE_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${ADMIN_ROLE}') THEN
        CREATE ROLE ${ADMIN_ROLE} LOGIN PASSWORD '${ADMIN_PASSWORD}' NOSUPERUSER CREATEDB CREATEROLE INHERIT;
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${APP_DB} TO ${READ_ROLE}, ${WRITE_ROLE}, ${ADMIN_ROLE};
GRANT USAGE ON SCHEMA public TO ${READ_ROLE}, ${WRITE_ROLE}, ${ADMIN_ROLE};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${READ_ROLE};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${READ_ROLE};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${WRITE_ROLE};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${WRITE_ROLE};

GRANT ALL PRIVILEGES ON SCHEMA public TO ${ADMIN_ROLE};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${ADMIN_ROLE};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${ADMIN_ROLE};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${ADMIN_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${READ_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${READ_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${WRITE_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${WRITE_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${ADMIN_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${ADMIN_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${ADMIN_ROLE};

ALTER SCHEMA public OWNER TO ${ADMIN_ROLE};
SQL
